version: '3.9'

services:
    myclass-pg:
        image: postgres:17.4
        volumes:
            - ./init/test.sql:/docker-entrypoint-initdb.d/test.sql
        networks:
            - myclass-network
        ports:
            - '5433:5432'
        environment:
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_USER=${DB_USERNAME}
    # myclass-back:
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     ports:
    #         - '${APP_PORT}:${APP_PORT}'
    #     networks:
    #         - myclass-network

networks:
    myclass-network:
        driver: bridge
